# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    assignees:
      - "clouddrove-ci"
    reviewers:
      - "approvers"

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "examples/basic" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "examples/complete" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "examples/spot_instance" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"

