---
name: Auto merge
on:
  pull_request:
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_merge.yml@1.0.10
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      tfcheck: 'spot_instance / Check code format'
...
